### ISSUE TITLE
Style CTR's movable back and forward buttons

### ISSUE THREAD

**Issue by mcdavis941** [mcdavis941/nnl-ctr-stylesheet#2]

**Comment by silverwind** [comment]
I think you could probably close the other similar issues about toolbarbuttons and use just this one if they can be handled by the same methods. Here's the fix I've posted:

``` css
#ctraddon_stop-button .toolbarbutton-icon { filter: invert(100%); }
#ctraddon_reload-button .toolbarbutton-icon { filter: invert(100%); }
#ctraddon_back-button .toolbarbutton-icon { filter: invert(100%); }
#ctraddon_forward-button .toolbarbutton-icon { filter: invert(100%); }
```

My concerns about this:
- Icons are a bit too bright, maybe use 80% invert to darken them slightly.
- Inactive buttons should have a darker icon. Is there a special selector for button state?
